site_name: MacroBase Documentation
docs_dir: source

pages:
  - Home: 'index.md'
  - User Guide:
    - 'Tutorial': 'user-guide/tutorial.md'
    - 'Common Parameters': 'user-guide/parameters.md'
    - 'Advanced Configuration': 'user-guide/advanced-configuration.md'
    - 'MacroBase SQL': 'user-guide/sql.md'
    - 'MacroBase SQL Workshop': 'user-guide/sql-workshop.md'

theme:
  name: 'readthedocs'
